### ISSUE TITLE
Article code fails in "Use the SharePoint JavaScript APIs to work with SharePoint data"

### ISSUE THREAD

**Issue by simonyarde** [OfficeDev/SharePoint_SP-hosted_Add-Ins_Tutorials#3] opened 2017-01-09 16:39 UTC
Hi

This code from the article doesn't work as expected:

```
'use strict';

var clientContext = SP.ClientContext.get_current(); 
var employeeList = clientContext.get_web().get_lists().getByTitle('New Employees In Seattle'); 
var completedItems; 
```

It will work when ClientContext is available:

```
'use strict';

var clientContext;
var employeeList;
var completedItems;

SP.SOD.executeFunc('sp.js', 'SP.ClientContext', function () {

  clientContext = SP.ClientContext.get_current();
  employeeList = clientContext.get_web().get_lists().getByTitle('New Employees In Seattle');
});
```

**Comment by Rick-Kirkham** [comment] 2017-01-10 18:22
I cannot reproduce this. Can you tell me what error message or symptom you got before you made the change?

**Comment by simonyarde** [comment] 2017-01-10 21:25
Function `get_current` was undefined.

I'll run it again when I get back to the office and send a screenshot if that would help.

**Comment by Rick-Kirkham** [comment] 2017-01-14 00:05
Keeping the project templates in VS consistent with the latest guidance has always been a challenge. The SOD system is primarily intended to avoid repeat loadings of the same file. I believe that at the time the "App for SharePoint" project template was created, the thinking was that the user must have opened some SP page or s/he wouldn't be able to launch the app (add-in), so that sp.js would very likely have loaded with that first SP page. 

At the time the tutorial was written, however, the advice from the SharePoint product team was to avoid using SOD. 

At any rate, if I understand your last comment, you're saying that the tutorial code does work, if a user downloads the project from this repo, as distinct from creating a new SP project in VS, so I'm closing this.

BTW, in VS 2015, the "App for SharePoint" project is now called "SharePoint Add-in". It still has the same ScriptLink in Default.aspx, but the App.js file now looks like this:
```
'use strict';

ExecuteOrDelayUntilScriptLoaded(initializePage, "sp.js");

function initializePage()
{
    var context = SP.ClientContext.get_current();    
      // stuff omitted
    }
}
```

**Comment by simonyarde** [comment] 2017-01-16 11:03
Yes, the issue is with the tutorial, which I understood was integral with the code.

If the instructions are followed with Visual Studio 2015 or later it won't work:

```
Create the add-in project
Start Visual Studio using the Run as administrator option.
Choose File > New > New Project.
```

**Comment by Rick-Kirkham** [comment] 2017-01-16 19:01
Thanks. That clarifies things. I have added steps to both the 1st and 9th tutorials which should ensure that the sp.js script is loaded in Default.aspx in the way that the project seems to require. The new versions should be published in the next couple of days.

**Closed** 2017-01-16 21:11 UTC
